#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) the edtf contributors
# SPDX-License-Identifier: MIT OR Apache-2.0
# Run `task release:prepare` on the open Release PR and push the result
# (issue #121).
#
# Every Release PR fails the lint gate until the extension upgrade script
# and fuzz/Cargo.lock are regenerated — both sit outside release-plz's
# reach, prepare-release.sh does both, and until now a person ran it by
# hand on every single release. This step closes that loop: it finds the
# Release PR that release-plz just opened or updated, runs the preparation
# on its branch, and pushes only if something changed.
#
# What it must NOT do is invent SQL. prepare-release.sh refuses when
# schema.snapshot.sql has moved, because writing that migration is a
# judgement call — this wrapper propagates that refusal as a loud failure
# on the Release PR rather than papering over it. Automation covers the
# proven-no-op case (every release so far); a person still owns the rest.
#
# The require-signed-commits ruleset targets ~DEFAULT_BRANCH only, so this
# bot commit on the release branch does not trip it.
set -euo pipefail

GITHUB_REPOSITORY="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY must be set}"
GH_TOKEN="${GH_TOKEN:?GH_TOKEN must be set (RELEASE_PLZ_TOKEN)}"

# The Release PR is identified by its title convention, not by branch name:
# release-plz's branch naming is an implementation detail, the title
# (`chore: release v<version>`) is the contract this repository already
# relies on elsewhere (release-pr skip guard, conventional commits).
BRANCH=""
BRANCH=$(gh pr list --repo "${GITHUB_REPOSITORY}" --state open \
  --json headRefName,title \
  --jq '[.[] | select(.title | startswith("chore: release"))] | .[0].headRefName // ""')

if [[ -z ${BRANCH} ]]; then
  echo "::notice::no open Release PR; nothing to prepare"
  exit 0
fi

echo "::notice::preparing Release PR branch ${BRANCH}"

git fetch origin "${BRANCH}"
git checkout -B "${BRANCH}" "origin/${BRANCH}"

# The script, not the task wrapper: this job installs only its own tools
# (canon rule), and the Taskfile entry is a bare passthrough to the script.
.github/scripts/prepare-release.sh

DIRTY=""
DIRTY=$(git status --porcelain) || DIRTY=""
if [[ -z ${DIRTY} ]]; then
  echo "::notice::already prepared; nothing to push"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Explicit paths, never -A (repository convention). The two files
# prepare-release.sh can touch are the upgrade SQL and fuzz/Cargo.lock,
# plus the gate's RELEASED list it appends to.
git add crates/edtf-postgres/sql fuzz/Cargo.lock .github/scripts/assert-upgrade-path.sh
git commit -m "chore: prepare release artifacts

Generated by auto-prepare-release.sh (issue #121): the extension upgrade
script and fuzz/Cargo.lock, the two chores release-plz cannot do."

# Push with the PAT the workflow provides — the same token release-plz used
# to create the branch, so pushing to it triggers the same CI a human's
# push would.
gh auth setup-git
git push origin "${BRANCH}"
echo "::notice::pushed release preparation to ${BRANCH}"
