#!/usr/bin/env bash
# Do the two things a Release PR always needs and release-plz cannot do.
#
# release-plz bumps manifests, changelogs and the workspace lockfile. Two
# things sit outside its reach, and both fail the lint gate on every single
# release PR until a human does them by hand:
#
#   1. The extension upgrade script. `default_version` is @CARGO_VERSION@, so
#      every release mints a new extension version and needs an
#      `edtf_postgres--<prev>--<new>.sql` for ALTER EXTENSION UPDATE to have
#      a path. Empty is correct whenever the SQL surface did not move.
#   2. fuzz/Cargo.lock. fuzz/ is `exclude`d from the workspace, so release-plz
#      cannot see it and its edtf-core pin goes stale on every bump.
#
# Doing them by hand, twice per release, is exactly the recurring chore this
# repository is supposed to have stopped having. Run this on the release
# branch instead:
#
#     task release:prepare
#
# It refuses to invent SQL. If the surface HAS moved, the snapshot diff says
# so and the script stops — writing that migration is a judgement call and
# belongs to a person.
set -euo pipefail

CRATE_DIR="crates/edtf-postgres"
SQL_DIR="${CRATE_DIR}/sql"
GATE=".github/scripts/assert-upgrade-path.sh"

VERSION=""
VERSION=$(cargo pkgid --manifest-path "${CRATE_DIR}/Cargo.toml" | sed 's/.*[@#]//')

# The previous version is the last entry currently in the gate's RELEASED
# list — which is authoritative precisely because the gate refuses to pass
# until the current version has been appended to it.
PREV=""
PREV=$(sed -n 's/^RELEASED=(\(.*\))$/\1/p' "${GATE}" | tr ' ' '\n' | tail -1)

if [[ -z ${VERSION} || -z ${PREV} ]]; then
  echo "::error::could not resolve version (${VERSION:-?}) or previous (${PREV:-?})"
  exit 1
fi

if [[ ${VERSION} == "${PREV}" ]]; then
  echo "::notice::${VERSION} is already prepared; nothing to do"
  exit 0
fi

echo "preparing ${PREV} -> ${VERSION}"

# 1. The upgrade script, but only when the surface is unchanged.
script="${SQL_DIR}/edtf_postgres--${PREV}--${VERSION}.sql"

if [[ -f ${script} ]]; then
  echo "ok  ${script} already exists"
else
  SNAPSHOT_CHANGED=""
  SNAPSHOT_CHANGED=$(git diff --name-only origin/main -- "${CRATE_DIR}/schema.snapshot.sql") || SNAPSHOT_CHANGED=""

  if [[ -n ${SNAPSHOT_CHANGED} ]]; then
    echo "::error::the SQL surface changed in this release"
    echo "::error::${script} needs real statements, not an empty file — write it by hand"
    git diff origin/main -- "${CRATE_DIR}/schema.snapshot.sql"
    exit 1
  fi

  cat > "${script}" << EOF
-- edtf_postgres ${PREV} -> ${VERSION}
--
-- Intentionally a no-op. \`default_version\` is @CARGO_VERSION@, so every
-- release mints a new extension version whether or not the SQL surface
-- moved; this file exists so \`ALTER EXTENSION edtf_postgres UPDATE\` has a
-- path to walk, not because anything needs doing.
--
-- Generated by prepare-release.sh, which refuses to write this file when
-- schema.snapshot.sql has changed — so its emptiness is a checked fact
-- rather than an assumption.
EOF
  echo "ok  wrote ${script}"
fi

# 2. RELEASED, so the gate checks the NEXT release against this one.
if ! grep -q "^RELEASED=(.* ${VERSION})$" "${GATE}"; then
  # macOS sed needs the empty -i argument; GNU sed tolerates it via --.
  sed -i.bak "s/^RELEASED=(\(.*\))$/RELEASED=(\1 ${VERSION})/" "${GATE}"
  rm -f "${GATE}.bak"
  echo "ok  appended ${VERSION} to RELEASED"
fi

# 3. fuzz/Cargo.lock, which release-plz cannot reach.
cargo metadata --manifest-path fuzz/Cargo.toml --format-version 1 > /dev/null
echo "ok  refreshed fuzz/Cargo.lock"

# Prove it, rather than announce it.
"${GATE}"
cargo metadata --manifest-path fuzz/Cargo.toml --locked --format-version 1 > /dev/null
echo "::notice::release ${VERSION} prepared — commit these changes to the release PR"
