CREATE FUNCTION "edtf_canonical"( "input" TEXT ) RETURNS TEXT IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_canonical_wrapper';
CREATE FUNCTION "edtf_level"( "input" TEXT ) RETURNS INT IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_level_wrapper';
CREATE FUNCTION "edtf_max"( "input" TEXT ) RETURNS date IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_max_wrapper';
CREATE FUNCTION "edtf_min"( "input" TEXT ) RETURNS date IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_min_wrapper';
CREATE FUNCTION "edtf_relation"( "a" TEXT, "b" TEXT ) RETURNS TEXT[] IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_relation_wrapper';
CREATE FUNCTION "edtf_valid"( "input" TEXT ) RETURNS bool IMMUTABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'edtf_valid_wrapper';
